// Flat config — the format Expo has defaulted to since SDK 53.
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const eslintPluginPrettierRecommended = require('eslint-plugin-prettier/recommended');

module.exports = defineConfig([
  expoConfig,
  eslintPluginPrettierRecommended,
  {
    rules: {
      // Surfaces the accidental `useEffect` dependency bugs this codebase is
      // most exposed to (theme objects, store selectors) as errors, not hints.
      'react-hooks/exhaustive-deps': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // The backend is a separate Vercel project with its own tsconfig and deps.
    // `expo-env.d.ts` is generated by the Expo CLI (and gitignored).
    ignores: ['dist/*', '.expo/*', 'android/*', 'ios/*', 'backend/*', 'expo-env.d.ts'],
  },
]);
